### ISSUE TITLE
Empty file

### ISSUE THREAD

**Issue by boeckMt** [steveoh/grunt-esri-slurp#31]
After running the command "grunt slurp" the file esri/arcgis/utils.js was empty
but it's available on http://js.arcgis.com/3.11amd/esri/arcgis/utils.js

**Comment by sfabijanski** [comment]
I see this thread is a few months old but thought I'd chime in, since I just tracked down some intermittent failures deploying my app to an empty utils.js file. I'm running Jenkins on a Centos 7 VM and developing on a Fedora 21 laptop. Builds would complete in both environments without errors (including esri-slurp). 

 On the CI server, sometimes the app is failing to load properly with the same code that built and runs fine on my laptop. My laptop is using a v0.11.14-pre instance of node. The Jenkins build project is using a 0.10.32 instance of node and js-beautify v1.5.5. In some cases, I can get the app to work from the CI server build simply by having Jenkins rebuild and deploy the project--no changes in the code. The project is running esri-slurp every build though so my esri folder is changing with every build. 

What's odd is that sometimes the build works and sometimes it doesn't. I have the server set to do nighly builds so I'll keep an eye on failures and see if the empty utils.js file is consistent between them. I'll also try upping the version of node on the CI server to see if that resolves the problem.
